config/routes.rb
Rails.application.routes.draw do
  mount Shoppe::Engine => "/shoppe"

  get 'product/:permalink' => 'products#show', :as => 'product'
  post 'buy/:permalink' => 'products#buy', :as => 'buy_product'
  get 'basket' => 'orders#show'
  delete 'basket' => 'orders#destroy'

  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :post]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :post]

  root :to => 'products#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
        redirect_to checkout_payment_path
      end
    end
  end

  def payment
    if request.post?
      redirect_to checkout_confirmation_path
    end
  end

  def confirmation
    if request.post?
      current_order.confirm!
      session[:order_id] = nil
      redirect_to root_path, :notice => "Order has been placed successfully!"
    end
  end

  def destroy
    current_order.destroy
    session[:order_id] = nil
    redirect_to root_path, :notice => "Basket emptied successfully."
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Shoppe::Product.root.ordered.includes(:product_category, :variants)
    @products = @products.group_by(&:product_category)
  end

  def show
    @product = Shoppe::Product.find_by_permalink(params[:permalink])
  end

  def buy
    @product = Shoppe::Product.find_by_permalink!(params[:permalink])
    current_order.order_items.add_item(@product, 1)
    redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Spareshop
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if has_order?
      %p{:style => "border:1px solid black;padding:10px;"}
        You have #{pluralize current_order.total_items, 'item'} in your basket which cost
        \#{number_to_currency current_order.total_before_tax}.
        = link_to "View basket", basket_path
      = link_to "Checkout", checkout_path
    = yield

app/views/orders/_items.html.haml
%table{:border => "1", :width => "100%"}
  %thead
    %tr
      %td Quantity
      %td Product
      %td Sub-Total
      %td Tax
      %td Total
  %tbody
    - order.order_items.each do |item|
      %tr
        %td= item.quantity
        %td= item.ordered_item.full_name
        %td= number_to_currency item.sub_total
        %td= number_to_currency item.tax_amount
        %td= number_to_currency item.total
    - if order.delivery_service
      %tr
        %td
        %td= order.delivery_service.name
        %td= number_to_currency order.delivery_price
        %td= number_to_currency order.delivery_tax_amount
        %td= number_to_currency order.delivery_price + order.delivery_tax_amount
  %tfoot
    %tr
      %td{:colspan => "4"} Sub-Total
      %td= number_to_currency order.total_before_tax
    %tr
      %td{:colspan => "4"} Tax
      %td= number_to_currency order.tax
    %tr
      %td{:colspan => "4"} Total
      %td= number_to_currency order.total

app/views/orders/checkout.html.haml
%h2 Checkout
= render 'items', :order => @order
= form_for @order, :url => checkout_path do |f|
  %dl
    %dt= f.label :first_name, 'Name'
    %dd
      = f.text_field :first_name
      = f.text_field :last_name
    %dt= f.label :billing_address1, 'Address'
    %dd= f.text_field :billing_address1
    %dd= f.text_field :billing_address2
    %dd= f.text_field :billing_address3
    %dd= f.text_field :billing_address4
    %dd= f.text_field :billing_postcode
    %dd= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true
    %dt= f.label :email_address
    %dd= f.text_field :email_address
    %dt= f.label :phone_number
    %dd= f.text_field :phone_number
    %dd= f.submit 'Continue'

app/views/orders/confirmation.html.haml
%h2 Place your order
= render 'items', :order => current_order
= button_to "Place order"

app/views/orders/payment.html.haml
%h2 Make your payment
= form_tag do
  %dl
    %dt= label_tag 'card_number'
    %dd= text_field_tag 'card_number'
    %dt= label_tag 'expiry'
    %dd= text_field_tag 'expiry'
    %dt= label_tag 'security_code'
    %dd= text_field_tag 'security_code'
    %dd= submit_tag "Continue"

app/views/orders/show.html.haml
%h2 Your basket
= render 'items', :order => current_order
%p= link_to 'Empty basket', basket_path, :method => :delete

app/views/products/index.html.haml
%h2 Products
- @products.each do |category, products|
  %h3= category.name
  %ul
    - products.each do |product|
      %li
        %h4= link_to product.name, product_path(product.permalink)
        %p= product.short_description
        %p
          %b Price:
          = number_to_currency product.price

app/views/products/show.html.haml
%h2= @product.name
- if @product.default_image
  = image_tag @product.default_image.path, :width => '200px', :style => "float:right"
%p= @product.short_description
%p
  %b= number_to_currency @product.price
  = link_to "Add to basket", buy_product_path(@product.permalink), :method => :post
%hr/
= simple_format @product.description
%hr/
%p= link_to "Back to list", root_path